version: "3.9"

services:
  portfolio-alexloup:
    build: .
    container_name: portfolio-alexloup

    restart: unless-stopped

    expose: 
      - "4000"
    
    networks:
      - proxy
  
networks:
  proxy:
    external: true